### PR TITLE
Text variables

### PR DESCRIPTION
**Pull request by DavidKeanu**

### CODE REVIEW

**Review by hstaatsxx — APPROVED** [review]
Looks great :) I just reformatted the code with formatter. 
---------------------------------------------------------

I would suggest to change some words in the English edition to match the current Angular version app.
Legal Notice -> Imprint
All issues -> All **I**ssues
About -> About **U**s
Support us -> Support **U**s

**Comment by hstaatsxx** [comment]
https://user-images.githubusercontent.com/31039939/208761542-7420d51e-c237-4628-81a3-358ca8d98f29.mov

Tested the implemented functionality + added suggested wording.

**Comment by DavidKeanu** [comment]
Good changes. @hstaatsxx you ok if I merge this ticket?

**Comment by hstaatsxx** [comment]
HI @DavidKeanu ,
I suggested but didn't upload those changes. I will change it and upload than merge it.

**Pull request merged**
