### PR TITLE
141 settings as modal

### LINKED ISSUE #137: change "Theme" to "Mode / Modus"

### PR DESCRIPTION
**Pull request by olierxleben**
Pull Request fixes some issues with the settings menu. 

I applied settings to not trigger side menu in swipe #145 

I applied language values for settings according to meeting on 13.03.23 which fixes #137 and #138

### CODE REVIEW

**Comment by olierxleben** [comment]
Hi, there is still one issue if we change navigation style, we should reload the page to set these styles accordingly.

**Review by sandra0503 — APPROVED** [review]

**Comment by sandra0503** [comment]
> Hi, there is still one issue if we change navigation style, we should reload the page to set these styles accordingly.

maybe it's enough to re-render the page or to manually push the route? 🤔

**Comment by sandra0503** [comment]
I think we can delete SettingsPage then?

**Comment by olierxleben** [comment]
I want to show these changes to the rest of the team before cleaning up. Cool with that?

**Comment by olierxleben** [comment]
> > Hi, there is still one issue if we change navigation style, we should reload the page to set these styles accordingly.
> 
> 
> 
> maybe it's enough to re-render the page or to manually push the route? 🤔

I will give it a try

**Pull request merged**
